spring:
  application:
    name: eureka-server
  profiles:
    active: local

---
spring:
  profiles: local
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000

---
spring:
  profiles: 8761

server:
  port: 8761

eureka:
  instance:
    hostname: node1
    instance-id: ${spring.application.name}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://node2:8762/eureka/,http://node3:8763/eureka/

---
spring:
  profiles: 8762

server:
  port: 8762

eureka:
  instance:
    hostname: node2
    instance-id: ${spring.application.name}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://node1:8761/eureka/,http://node3:8763/eureka/

---
spring:
  profiles: 8763

server:
  port: 8763

eureka:
  instance:
    hostname: node3
    instance-id: ${spring.application.name}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://node1:8761/eureka/,http://node2:8762/eureka/