server:
  port: 8009

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.geekymv.springcloud.model
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true

spring:
  application:
    name: product-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.56.102:3306/eshop?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Qwer!@#$1234

  # ehcache
    cache:
      ehcache:
        enabled: true
        config: classpath:ehcache.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true

management:
  endpoint:
    health:
      show-details: always

info:
  appName: product-service