server:
  port: 8001

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.geekymv.springcloud.model
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true

spring:
  application:
    name: product-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/eshop?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000

  # redis
  redis:
    database: 10
    timeout: 5s
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 20
        min-idle: 5
        max-wait: 5s
        max-idle: 10

  # ehcache
    cache:
      ehcache:
        enabled: true
        config: classpath:ehcache.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true

management:
  endpoint:
    health:
      show-details: always

info:
  appName: product-service

logging:
  level:
    com.geekymv.springcloud: debug
