server:
  port: 8091

spring:
  application:
    name: gateway-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true


zuul:
  prefix: /sample
  retryable: true
  ignoredServices: '*'
  routes:
    app:
      path: /app/**
      service-id: app-rest
      strip-prefix: false
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000

ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 6000
