server:
  port: 8080

spring:
  application:
    name: app-rest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true
